### ISSUE TITLE
Cannot link cosmetic wooden carts

### ISSUE THREAD

**Issue by liach** [hanakocz/RailCraft-Cosmetic-Additions-2#10]

**Comment by hanakocz** [comment]
I cannot reproduce this thing, it works correctly to me. Those carts do make connected trains correctly. At least for pure RailCraft + RCC installation only...

**Comment by Cassiobsk8** [comment]
It's working for me, the only thing is that it breaks the link if the carts go to a chunk that is not loaded but this I think is a railcraft bug.

I found this: https://gfycat.com/SaltyScentedAfricangroundhornbill

**Comment by liach** [comment]
you referenced the wrong issue

**Comment by Cassiobsk8** [comment]
@liach Sorry, as you gave no description I thought it was the same problem that happened to me as sometimes the carts do not link together on the server
I'm going to remove the reference.

**Comment by hanakocz** [comment]
Only time when linking is not working for me is on Abandoned tracks, which is a feature, not a bug(of RC itself). If you won't add any more info, I will consider this as not relevant.
