### ISSUE TITLE
Linked carts should inherit destination from locomotive

### ISSUE THREAD

**Issue by brotazoa** [hanakocz/RailCraft-Cosmetic-Additions-2#4]
Path signals correctly path locomotives with destinations, but see linked carts pulled by those locomotives as having no destination, which caused the 'cart on track without destination' state for the signal. Suggestion is to treat linked carts as having same destination as locomotive.

**Comment by brotazoa** [comment]
Please delete. Had multiple tabs open, posted issue in wrong one. I feel like such a noob.
link to correct repo if interested :: https://github.com/MineMaarten/Signals

**Comment by hanakocz** [comment]
No problem. If I can help with that somehow, then just write me. However I probably won't be able to fix things that will behave same with pure RailCraft carts (but we can still talk about them if needed)
