### ISSUE TITLE
Traincraft compatability issue.

### ISSUE THREAD

**Issue by Bendragon1337** [hanakocz/RailCraft-Cosmetic-Additions-2#7]
Traincraft seems to be incompatible with this mod whereas railcraft seems to be compatible with traincraft.

**Comment by hanakocz** [comment]
What about some details? What exactly is incompatible? I have not played with Traincraft...

**Comment by Ristellise** [comment]
-_-

Traincraft and railcraft uses 2 seperate rail systems. also this is for 1.10 RCA instead of 1.7. thanks. @Hanakocz probably also want to mention that the switches from Railcraft or its addons are not compatible with traincraft in anyway :p

**Comment by hanakocz** [comment]
Closed as not contructive, we got no information whatsoever, what is not compatible...
