### ISSUE TITLE
Crash when I right click on the platform block on the server

### ISSUE THREAD

**Issue by Cassiobsk8** [hanakocz/RailCraft-Cosmetic-Additions-2#8]
Only the client crashes

https://pastebin.com/JwxSeWpt

**Comment by hanakocz** [comment]
Oh, it looks like the last publicly released version of RailCraft misses Spike Mauls. I will try to cnvince @CovertJaguar to release new version soon.

**Comment by Cassiobsk8** [comment]
the beta version is ready but only for patreons.
Thanks for the quick response!

**Comment by hanakocz** [comment]
Yes in betas this item is already in, I did not checked when it was added, sorry! It was probably added with track junctions. I will see if I can make something with that to prevent crashes but keep it working (probably solution is to put minimum version of RC higher , but that needs public release)

**Comment by hanakocz** [comment]
fixed by build 3.0.5. RC has new public build, it is mandatory to get it to run this version (so no items are missing)
